Add "Share Presently" on settings menu
alisonthemonster/GratitudeJournal pull request #121
Opened 2020-08-26 02:56 UTC by polbins

## :scroll: Description

Add a share item on the Settings Menu, closes https://github.com/alisonthemonster/Presently/issues/92

other changes:
- update the project to Android Studio 4.0.1
- update to Kotlin 1.4.0
- update all the libraries with warnings (did some smoke testing as well after the changes)
- attempt to auto-translate the strings via Google Docs + Google Translate 
    - This is the spreadsheet that I used, https://docs.google.com/spreadsheets/d/12ir2uvl1y2Z8RDKev6X0p_dYlsG8uuRGeNSLXXhsffw/edit?usp=sharing

## :green_heart: How did you test it?
Manual Test on Emulator w/ API 30

## :camera_flash: Screenshots / GIFs

<img src="https://user-images.githubusercontent.com/883468/91249950-de716100-e725-11ea-9e34-8a48d24701dd.png" width="260">

2020-08-29 22:16 UTC, alisonthemonster requested changes
Overall this looks great! Just have a few little style requests.

As for translations that is what I usually do as well. 

Thank you thank you thank you!

2020-08-29 22:16 UTC, alisonthemonster commented on app/src/main/java/journal/gratitude/com/gratitudejournal/ui/dialog/CelebrateDialogFragment.kt
> +            startActivity(Intent.createChooser(share, getString(R.string.share_your_gratitude)))
Yay! Thank you for this!

2020-08-29 22:16 UTC, alisonthemonster commented on app/src/main/java/journal/gratitude/com/gratitudejournal/ui/settings/SettingsFragment.kt
> +        val share = findPreference<Preference>("share_app")
I know I haven't followed this rule everywhere but let's use a constant in the companion object for this key. (I'll make a PR to update the rest of the places I used strings instead of constants!)

2020-08-29 22:16 UTC, alisonthemonster commented on app/src/main/java/journal/gratitude/com/gratitudejournal/ui/settings/SettingsFragment.kt
> +
Small nit: can we remove this white space here?

2020-08-29 22:16 UTC, alisonthemonster commented on app/src/main/java/journal/gratitude/com/gratitudejournal/ui/settings/SettingsFragment.kt
> +        firebaseAnalytics.logEvent(OPENED_SHARE_APP, null)
Yay for including analytics events!

2020-08-31 03:17 UTC, polbins commented on app/src/main/java/journal/gratitude/com/gratitudejournal/ui/settings/SettingsFragment.kt
> +        val share = findPreference<Preference>("share_app")
What do you feel about using String resources instead? What I like about using String resources is that you only have one reference for everything. Compared to constants where it can only be used in code, but there may still be typos when writing in XML.

Please see my recent commit!

2020-08-31 03:20 UTC, polbins commented
> Overall this looks great! Just have a few little style requests.
> 
> As for translations that is what I usually do as well.
> 
> Thank you thank you thank you!

Thanks for the great app that you've made! I've been using it daily for 25 days now (I'm on a streak, wuhoo!) and this is my small way of showing my "gratitude" :) 

Looking forward to build new features and/or refactor!

2020-09-01 02:02 UTC, alisonthemonster commented on app/src/main/java/journal/gratitude/com/gratitudejournal/ui/settings/SettingsFragment.kt
> +        val share = findPreference<Preference>("share_app")
Looks awesome, even better! I'll kick off the rest of CI now :)

2020-09-01 02:02 UTC, alisonthemonster approved these changes

2020-09-01 02:20 UTC, merged