Localization - Afrikaans [afr]
alisonthemonster/GratitudeJournal pull request #208
Opened 2021-05-23 09:30 UTC by JonathanAspeling

## :scroll: Description!
I added English to Afrikaans Translation. Which includes:

- Store Listing in Afrikaans
- Prompts in Afrikaans
- UI text to Afrikaans

_Elected to not translate quotes - they tend to not read/mean the same as when in original English_

## :green_heart: How did you test it?
Manual - Tested with Afrikaans spell checkers and colleagues to ensure grammar is correct.

## :camera_flash: Screenshots / GIFs

[image](https://user-images.githubusercontent.com/42679894/119255104-22609c00-bbba-11eb-89a2-4ccccf3aee9d.png)

2021-05-23 09:40 UTC, JonathanAspeling commented
Ah - thank goodness for automated testing - I think I see the issue.

2021-05-23 10:03 UTC, JonathanAspeling commented
Hehe cool not sure where I'm missing things :D But welcome to let me know and I'll fix and commit

2021-06-02 03:58 UTC, alisonthemonster requested changes
Left some comments about some string character escpaing and a few missing translations. Thank you so much for doing this translation and for figuring out my new module structure! I'll be updating the guide for translators hopefully soon!

2021-06-02 03:58 UTC, alisonthemonster commented on app/src/main/res/values/strings.xml
> +    <string name="language_af" translatable="false">Afrikaans</string>
Oh you made me realize we have these files in the `app` module in addition to the `strings` module, I'll fix that in another PR!

2021-06-02 03:58 UTC, alisonthemonster commented on strings/src/main/res/values-af/prompts.xml
> +            <item>Het jy dalk 'n vriend vir wie jy dankbaar is?</item>
These are the issue you are having with CI! You need to escape the apostrophe characters like so:
```
<item>Het jy dalk \'n vriend vir wie jy dankbaar is?</item>
```

2021-06-02 03:58 UTC, alisonthemonster commented on strings/src/main/res/values-af/strings.xml
> +    <string name="select_a_theme">Kies 'n tema</string>
Here too!

2021-06-02 03:58 UTC, alisonthemonster commented on strings/src/main/res/values-af/strings.xml
> +    <string name="file_not_csv">Lêer moet 'n CSV wees</string>
Here 👋

2021-06-02 03:58 UTC, alisonthemonster commented on strings/src/main/res/values-af/strings.xml
> +    <string name="fingerprint_error_lockout_too_many">Te veel pogings tot biometriese verifikasie. Probeer asseblief oor 'n paar minute weer.</string>
Here!

2021-06-02 03:58 UTC, alisonthemonster commented on strings/src/main/res/values-af/strings.xml
> +    <string name="dropbox_setting_title">Maak 'n rugsteun van u data met Dropbox</string>
This one too!

2021-06-02 03:58 UTC, alisonthemonster commented on strings/src/main/res/values-af/strings.xml
> +    <string name="import_summary">Kies 'n gerugsteunde CSV-lêer om in te voer</string>
And finally this one!

2021-06-02 03:58 UTC, alisonthemonster commented on strings/src/main/res/values-af/strings.xml
> +    <string name="share_app_text">Oefen dankbaarheid met hierdie eenvoudige, altyd gratis en private dankbaarheidsjoernaal app</string>
I also noticed there are a few translations missing here, would you mind adding these?
```
    <string name="app_language_title">Application language</string>
    <string name="app_language_summary">Set default app language</string>
    <string name="loading_lang">Loading language, please wait</string>
    <string name="show_quote_off">Gratitude quotes will not be shown on entry page</string>
    <string name="show_quote_on">Gratitude quotes will be shown on entry page</string>
    <string name="inspiration_title">Inspirational quotes</string>
```

2021-06-02 15:46 UTC, JonathanAspeling commented
Awesome it's a pleasure! Will attend to it first chance!

2021-09-02 17:44 UTC, JonathanAspeling commented on app/src/main/res/values/strings.xml
> +    <string name="language_af" translatable="false">Afrikaans</string>
100% Not sure if sorted as yet - think I have the latest version of code base :D Let me know if I have an action point here - not seeing something specific

2021-09-02 17:46 UTC, JonathanAspeling commented on strings/src/main/res/values-af/prompts.xml
> +            <item>Het jy dalk 'n vriend vir wie jy dankbaar is?</item>
Brilliant! I think this is to match with Regex? - Have made the change will push up soonest

2021-09-02 17:46 UTC, JonathanAspeling commented on strings/src/main/res/values-af/strings.xml
> +    <string name="select_a_theme">Kies 'n tema</string>
Cheers! Got em!

2021-09-02 17:47 UTC, JonathanAspeling commented on strings/src/main/res/values-af/strings.xml
> +    <string name="file_not_csv">Lêer moet 'n CSV wees</string>
Got them! Thanks!

2021-09-02 17:48 UTC, JonathanAspeling commented on strings/src/main/res/values-af/strings.xml
> +    <string name="fingerprint_error_lockout_too_many">Te veel pogings tot biometriese verifikasie. Probeer asseblief oor 'n paar minute weer.</string>
Cheers thanks for having taken the time to highlight! Appreciate

2021-09-02 17:48 UTC, JonathanAspeling commented on strings/src/main/res/values-af/strings.xml
> +    <string name="dropbox_setting_title">Maak 'n rugsteun van u data met Dropbox</string>
Perfect got it!

2021-09-02 17:48 UTC, JonathanAspeling commented on strings/src/main/res/values-af/strings.xml
> +    <string name="import_summary">Kies 'n gerugsteunde CSV-lêer om in te voer</string>
Shot! Got it!

2021-09-02 17:58 UTC, JonathanAspeling commented on strings/src/main/res/values-af/strings.xml
> +    <string name="share_app_text">Oefen dankbaarheid met hierdie eenvoudige, altyd gratis en private dankbaarheidsjoernaal app</string>
With pleasure! Done

2021-09-02 18:10 UTC, JonathanAspeling commented
Yass! CI Passed :D hope you're happy with the changes @alisonthemonster Again blown away by what you've put in place and developed 👏 

Apologies for the long the long turn around time here 😄  Baby and a recent promotion to Data Engineer has kept me so busy! Been sweating blood and tears balancing things and inevitably dropped some balls :D

Shout if there's anything else - feel free to @ me

2021-09-09 22:45 UTC, alisonthemonster commented on app/src/main/res/values/strings.xml
> +    <string name="language_af" translatable="false">Afrikaans</string>
You're okay, I never actually did remove the duplicated strings 🤦‍♀️

2021-09-09 22:45 UTC, alisonthemonster commented
Thank you so much for the changes and congrats on baby and promo! 👏 I've kicked off a CI build, will approve when its green!

2021-09-09 22:51 UTC, alisonthemonster approved these changes

2021-09-09 22:52 UTC, merged