add Brazilian Portuguese translation
alisonthemonster/GratitudeJournal pull request #85
Opened 2020-02-28 10:07 UTC by danilofreire

Hi Alison!

Thanks very much for your great app! I downloaded it today and I'm very happy with it. To express my gratitude, I'd like to share my Brazilian Portuguese translation. I know there's already a Portuguese translation in the repo (thanks to the translator!), but it doesn't sound very natural to Brazilian Portuguese speakers. So I've decided to add my own, but feel free to discard it if you don't think it's useful. I've translated all the required files plus the motivational quotes. The repository is titled `values-pt-br`. I'm happy to make any changes you think are necessary to make my files fully compatible with the original code. Again, many thanks for writing this lovely little app 😃

2020-03-01 19:35 UTC, alisonthemonster requested changes
Hello and thank you so much for this contribution! 

A few extra files can be deleted and I just need you to change your folder name from 'values-pt-br` to `values-pt-rBR` and then you're all set!

2020-03-01 19:35 UTC, alisonthemonster commented on StoreListing.md
> -احتفل بحياتك اليومية مع تطبيق برزنتلي، يومية الامتنان الالكترونية المجانية والخاصة.
Looks like you accidentally lost some Arabic here as well!

2020-03-01 19:35 UTC, alisonthemonster commented on app/src/main/res/values-pt-br/array.xml
> +</resources>
No need to translate this file :)

2020-03-01 19:35 UTC, alisonthemonster commented on app/src/main/res/values-pt-br/attrs.xml
> +</resources>
Same with this one! It can just be deleted.

2020-03-01 19:35 UTC, alisonthemonster commented on app/src/main/res/values-pt-br/colors.xml
> +</resources>
This file doesn't need a Portuguese version also.

2020-03-01 19:35 UTC, alisonthemonster commented on app/src/main/res/values-pt-br/ic_launcher_background.xml
> +</resources>
Same here!

2020-03-01 19:35 UTC, alisonthemonster commented on app/src/main/res/values-pt-br/styles.xml
> +</resources>
This file also isn't needed!

2020-03-02 04:08 UTC, danilofreire commented
Thank you very much for the feedback! Sorry for the mistakes, I will edit the files and create another pull request soon. I will close this one 😄

2020-03-02 04:08 UTC, closed without merging

2020-03-02 04:13 UTC, danilofreire commented on StoreListing.md
> -احتفل بحياتك اليومية مع تطبيق برزنتلي، يومية الامتنان الالكترونية المجانية والخاصة.
Thanks for pointing that out! I've just copied the text from your original file. Should be solved now :)